version: '3'

services:
  postgres:
    image: 'postgres:latest'
    container_name: 'java-postgres'
    environment:
      - 'POSTGRES_DB=contacts'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=admin'
    ports:
      - 5432:5432
